### ISSUE TITLE
Root domain record won't update

### ISSUE THREAD

**Issue by seniordevops7** [va1entin/tools#2]
Hi,

Trying to update the root domain record @ or example.com gives me the following error:

@
```
2022-11-04 15:33:25 ERROR: Could not find id of DNS record. "Results" in API response were empty. Please make sure that the specified DNS record already exists and config cloudflare_update_record_config.yaml is correct. Try again after. Dumping exception...
Traceback (most recent call last):
  File "/home/pi/scripts/cloudflare_update_record/cloudflare_update_record.py", line 148, in get_identifiers
    record_identifier = record_id_response.json()['result'][0]['id']
IndexError: list index out of range
```

example.com
```
2022-11-04 15:38:01 WARNING: record_name "example.com" in config "cloudflare_update_record_config.yaml" contains zone_name "example.com". This is not necessary and should be removed.
2022-11-04 15:38:03 ERROR: Could not find id of DNS record. "Results" in API response were empty. Please make sure that the specified DNS record already exists and config cloudflare_update_record_config.yaml is correct. Try again after. Dumping exception...
Traceback (most recent call last):
  File "/home/pi/scripts/cloudflare_update_record/cloudflare_update_record.py", line 148, in get_identifiers
    record_identifier = record_id_response.json()['result'][0]['id']
IndexError: list index out of range

```

**Comment by va1entin** [comment]
Hi @enmanuelmoreira 
thanks for the info!
I'll check it out asap. I'm only using the script for subdomains so I might've missed this indeed.

**Comment by va1entin** [comment]
In [8519412](https://github.com/va1entin/tools/commit/85194129dc1d869ffb6a20dde23381c309ec3f55) I have just commited an update that should enable the script to handle root records specified by `@` as `record_name` in the config. A test in my own DNS zone worked both for subdomains and the root domain with this new version.

Kindly have a look and test @enmanuelmoreira  :smiley:

**Comment by seniordevops7** [comment]
Awesome @va1entin! I've tested and it works.

Thank you so much!
